[versions]
agp = "8.9.2"
cameraCamera2 = "1.3.1"
cameraCore = "1.5.1"
cameraCoreVersion = "1.3.1"
cameraLifecycle = "1.3.1"
cameraView = "1.3.1"
concurrentFutures = "1.3.0"
faceDetection = "16.1.7"
faceDetectionVersion = "16.1.5"
firebaseFirestoreKtx = "25.1.4"
firebaseFirestoreKtxVersion = "25.0.0"
guava = "33.3.0-android"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
activity = "1.11.0"
constraintlayout = "2.2.1"
retrofit = "2.9.0"
tensorflowLite = "2.13.0"
tensorflowLiteSupport = "0.4.3"
googleGmsGoogleServices = "4.4.4"
firebaseFirestore = "26.0.2"
firebaseCrashlyticsBuildtools = "3.0.6"

[libraries]
camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "cameraCore" }
camera-camera2-v131 = { module = "androidx.camera:camera-camera2", version.ref = "cameraCamera2" }
camera-core = { module = "androidx.camera:camera-core", version.ref = "cameraCore" }
camera-core-v131 = { module = "androidx.camera:camera-core", version.ref = "cameraCoreVersion" }
camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "cameraCore" }
camera-lifecycle-v131 = { module = "androidx.camera:camera-lifecycle", version.ref = "cameraLifecycle" }
camera-view = { module = "androidx.camera:camera-view", version.ref = "cameraCore" }
camera-view-v131 = { module = "androidx.camera:camera-view", version.ref = "cameraView" }
concurrent-futures = { module = "androidx.concurrent:concurrent-futures", version.ref = "concurrentFutures" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
face-detection = { module = "com.google.mlkit:face-detection", version.ref = "faceDetection" }
face-detection-v1615 = { module = "com.google.mlkit:face-detection", version.ref = "faceDetectionVersion" }
firebase-firestore-ktx = { module = "com.google.firebase:firebase-firestore-ktx" }
firebase-firestore-ktx-v2500 = { module = "com.google.firebase:firebase-firestore-ktx", version.ref = "firebaseFirestoreKtxVersion" }
firebase-storage-ktx = { module = "com.google.firebase:firebase-storage-ktx" }
google-firebase-firestore-ktx = { module = "com.google.firebase:firebase-firestore-ktx", version.ref = "firebaseFirestoreKtx" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
tensorflow-lite = { module = "org.tensorflow:tensorflow-lite", version.ref = "tensorflowLite" }
tensorflow-lite-support = { module = "org.tensorflow:tensorflow-lite-support", version.ref = "tensorflowLiteSupport" }
firebase-firestore = { group = "com.google.firebase", name = "firebase-firestore", version.ref = "firebaseFirestore" }
firebase-crashlytics-buildtools = { group = "com.google.firebase", name = "firebase-crashlytics-buildtools", version.ref = "firebaseCrashlyticsBuildtools" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
google-gms-google-services = { id = "com.google.gms.google-services", version.ref = "googleGmsGoogleServices" }

